app = "pubg-tdm-frankfurt"

[build]
  image = "ubuntu:22.04"

[env]
  WG_CONF_PATH = "/etc/wireguard/wg0.conf"

[[services]]
  internal_port = 51820
  protocol = "udp"

  [[services.ports]]
    port = 51820